[build]
command = "npm run build:nolint"
publish = "out"

[build.processing]
  skip_processing = true # disables asset optimization which Next.js takes care of

[dev]
framework = "#custom"
command = "npm run dev"
port = 8080
targetPort = 3000
autoLaunch = true