// Function says: This file is generated by Next.js for TypeScript support, you can't remove it.
// You also don't want to edit it unless you know what you're doing.
// If your IDE / editor shows you errors in this file, you can probably ignore them.

/* eslint-disable spaced-comment */

/// <reference types="next" />
/// <reference types="next/types/global" />
